language: go

go:
    - 1.10.x

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs npm
    - npm install

install:
    - go get -u github.com/gopherjs/gopherjs github.com/mattn/go-sqlite3 github.com/jmoiron/sqlx
    - go get -u -d -tags=js github.com/flimzy/go-sql.js
    - go get -u gopkg.in/alecthomas/gometalinter.v2 && gometalinter.v2 --install
    # Syscall support
    - >
    ( cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/;
        npm install --global node-gyp;
        node-gyp rebuild;
        mkdir -p ~/.node_libraries/;
        cp build/Release/syscall.node ~/.node_libraries/syscall.node )

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - gometalinter.v2 --config .linter.json
    - go test -race github.com/flimzy/anki
    - gopherjs test github.com/flimzy/anki
